# Generated by Django 5.1.7 on 2025-03-31 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edificio1', models.CharField(max_length=100)),
                ('edificio2', models.CharField(max_length=100)),
                ('edificio3', models.CharField(max_length=100)),
                ('edificio4', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
