# Generated by Django 5.2 on 2025-04-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='autor',
            field=models.CharField(default='Stefany', max_length=100),
            preserve_default=False,
        ),
    ]
