# Generated by Django 5.1.7 on 2025-04-13 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Libro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='año_publicación',
            new_name='año_publicacion',
        ),
    ]
